### PR TITLE
Added documentation for molecular level MD use cases

### PR DESCRIPTION
**Pull request by adamhospital**

### CODE REVIEW

**Comment by lbologna** [comment]
Hello @adamhospital @alex4200,

I merged Adam's insertion in the dev. Could you please have a look?
https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/subcellular_level/synaptic_plasticity_pathways/synaptic_plasticity_pathways.html

@adamhospital I noticed that in the image there is some overlapping text? Is it possible to correct this so that axis labels are well visualized and not overlapped?

Thank you

**Comment by alex4200** [comment]
@adamhospital It looks good so far; the only thing I noticed is an incorrect link for the guidebook for "Small molecule force field parametrization for atomistic Molecular Dynamics simulations". In the first sentence there is a DB00458 link leading to a 404 page.

**Comment by adamhospital** [comment]
> Hello @adamhospital @alex4200,
> 
> I merged Adam's insertion in the dev. Could you please have a look?
> https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/subcellular_level/synaptic_plasticity_pathways/synaptic_plasticity_pathways.html
> 
> @adamhospital I noticed that in the image there is some overlapping text? Is it possible to correct this so that axis labels are well visualized and not overlapped?
> 
> Thank you

Hi Luca, the new online use cases documentations included in this pull request are:
guidebook/online_usecases/molecular_level/biobb_md/*.html 
not the subcellular_level :) 

-Adam-

**Comment by adamhospital** [comment]
> guidebook

Thanks for spotting that Alex, I missed the http:// at the beginning of the link. 
Should I make a new pull request with this small change?

**Comment by lbologna** [comment]
> > guidebook
> 
> Thanks for spotting that Alex, I missed the http:// at the beginning of the link.
> Should I make a new pull request with this small change?

@adamhospital sure, the Molecular lLevel! Sorry, I spotted some other compilation error and commented on the wrong link.
No need to generate a new pull request, I just inserted the http string and put it online. It works for me:
https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/molecular_level/biobb_md/ligand_param.html

@alex4200 @adamhospital waiting for green light to put everything in PROD.

**Comment by alex4200** [comment]
'Green light' from my side

**Comment by lbologna** [comment]
Thank you.
Put to PROD.

**Pull request merged**
