### PR TITLE
Added "Multicompartmental simulation of the cerebellum" guidebook

### PR DESCRIPTION
**Pull request by Helveg**
Adressed https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/538 and added a description of the usecase "Multicompartmental simulation of the cerebellum"

### CODE REVIEW

**Comment by lbologna** [comment]
Hello @Helveg, @alex4200,

I put the new insertions in DEV:
https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/brain_area_circuit_in_silico_experiments/cerebellum/multicompartmental_simulation/multicompartmental_simulation.html

Could you please check before pushing to Prod?

Thank you.

**Comment by alex4200** [comment]
@Helveg I have just one comment on the text. The second sentence does not make sense to me:

`Inputs arrive through the afferent mossy fibers onto the glomeruli *who the excitation of the granule cells*. `

Maybe you meant to write 

`Inputs arrive through the afferent mossy fibers onto the glomeruli which excites the granule cells. `

I appreciate if you can correct this sentence (or explain that is makes sense).

Thanks
Alex

**Comment by Helveg** [comment]
Yes sorry, that should be "which excite the granule cells"

**Comment by lbologna** [comment]
Hello @alex4200, @Helveg,

correction done and moved to PROD.

**Pull request merged**
