### PR TITLE
Nest desktop integration

### PR DESCRIPTION
**Pull request by bweyers**
Changed the structure and moved the folder for NEST Desktop up. Additionally, a smaller typo was fixed.

### CODE REVIEW

**Comment by lbologna** [comment]
Hello @bweyers, @alex4200, 

I integrated the last changes in the Guidebook and inserted NEST Desktop in the TOC:
https://lbologna.github.io/hbp-sp6-guidebook/index.html

I created a possible entry page to be inserted in the BSP, at this link (you should have write access):
https://collab.humanbrainproject.eu/#/collab/83329/nav/564364

Please feel free to modify it (by clicking on the top right wheel) as you see fit, before integrating it in the BSP.

Thanks.

**Comment by bweyers** [comment]
Thanks @lbologna! I was wondering how people find this landing page (https://collab.humanbrainproject.eu/#/collab/83329/nav/564364), such that it is easier for me to understand what kind of information should be provided there. In any case, I just added one sentence refering to the getting started documentation, which might be helpful.

**Comment by alex4200** [comment]
@bweyers Why not implement this usecase (the external page) directly in the BSP (like the PairRecording etc.). No need for an intermediate notebook. 

Also, the site https://nest-desktop.apps.hbp.eu/#/ seems to be down.

**Comment by bweyers** [comment]
@alex4200 yes, there is no need for an intermediate notebook. I think that is also the reason why @lbologna created a collab page which might run as landing page for NEST Desktop in the BSP. And yes, the page might be down due to work we are doing in the moment as we prepare NEST Desktop for the use in a course at Freiburg Uni. Thus, there might be times where it is down.

**Comment by lbologna** [comment]
Hello @alex4200,

yes the page https://collab.humanbrainproject.eu/#/collab/83329/nav/564364 is just a test one.

I will integrate it in the BSP once we agree on its final version (by the way, @bweyers for me the page is fine, if also Alex agrees I can create a new item in the BSP right away).
As for the positioning, being NEST a standalone, multi faceted application and given that we intend to have it highly visible to the users, we are going to place is on the main Online Use Case level (below the Highly Integrated Workflows).

**Comment by bweyers** [comment]
@lbologna Could you please push the page online? I would like to finish this work.

**Comment by lbologna** [comment]
Hello @bweyers,

the Guidebbok page is already online since a few days, sorry for not mentioning.
https://humanbrainproject.github.io/hbp-sp6-guidebook/online_usecases/nest_desktop/NESTDesktop.html
And the NEST Desktop is already in the BSP:
https://collab.humanbrainproject.eu/#/collab/1655/nav/565558

**Comment by bweyers** [comment]
@lbologna great! Could we then close the issue @alex4200 ?

**Comment by alex4200** [comment]
@bweyers  Yes, issue can be closed, looks all good to me. Thanks

**Comment by bweyers** [comment]
@alex4200 ok! I cannot close it, I guess this is done be @lbologna?

**Pull request merged**
