### PR TITLE
Add Network Reduction under Circuit Building

### PR DESCRIPTION
**Pull request by antonelepfl**

### CODE REVIEW

**Comment by antonelepfl** [comment]
This needs to be checked by Aleksei (from BBP) so I'll let you know when you can merge it.

**Comment by antonelepfl** [comment]
@lbologna I think we can try to merge this. Let us know if you have any issue.

**Comment by lbologna** [comment]
Hello @antonelepfl, @alex4200, 

I merged the pull request and did some changes (mostly formatted the references with links):
https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/circuit_building/hippocampus/network_reduction/network_reduction.html

Please let me know when we are ready for pushing to prod.
Thanks.

**Comment by alex4200** [comment]
I am ok for the changes to be pushed to prod

**Pull request merged**
