### PR TITLE
Improve brain area in-silico

### PR DESCRIPTION
**Pull request by antonelepfl**

### CODE REVIEW

**Comment by antonelepfl** [comment]
Hi Luca we discovered a small issue and here is the fix.
For next time I would really recommend that you fetch the content from the PR to build in GH_Pages instead of merging and building because this may happened as this time that I needed to create multiple PR to fix stuffs and we 'pollute' the master branch.

**Comment by lbologna** [comment]
Hello @antonelepfl,
yes sure. I used to merge and solve the conflict locally before re-pushing but I will go the way you suggest to avoid possible conflicts with master.
I pushed the html page to the dev deployment page:
https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/brain_area_circuit_in_silico_experiments/hippocampus/configure_run_brainregion_preconf_model_data/configure_run_brainregion_preconf_model_data.html

@antonelepfl, @alex4200 if it is fine with you I will update the PROD server

**Comment by alex4200** [comment]
@lbologna Yes I am happy with it, please update it to prod

**Comment by lbologna** [comment]
Done.

**Pull request merged**
