### PR TITLE
Add Neocortex documentation under Brain Area In Silico Experiments

### PR DESCRIPTION
**Pull request by antonelepfl**
- [ ] Add Report (PDF) produced by Vishal

### CODE REVIEW

**Comment by antonelepfl** [comment]
@lbologna Please wait before merging this because I need to add a report to this page.
I'll keep you updated

**Comment by alex4200** [comment]
@antonelepfl Is there any update on this issue?

**Comment by antonelepfl** [comment]
[Jira Ticket](https://bbpteam.epfl.ch/project/issues/browse/NSETM-967?focusedCommentId=115926&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-115926) We can probably wait until next week to see if there is any progress on that PDF file and if there is not, I will merge this and then I can add the PDF

**Comment by alex4200** [comment]
Agreed

**Comment by visood** [comment]
Is this PR related to the PDF report for the neocortical circuit?
The report should be available early June.

**Comment by antonelepfl** [comment]
> Is this PR related to the PDF report for the neocortical circuit?

Yes it is

@visood Do you have any update?

**Comment by visood** [comment]
We decided not to provide a PDF report. A report will be provided on the model website.

**Comment by antonelepfl** [comment]
Ok then we will merge this.
@lbologna could you see if everything is ok for the merge?

**Comment by lbologna** [comment]
Hello @alex4200, @antonelepfl,

I merged and put to Prod after correcting just a couple of typos:

https://humanbrainproject.github.io/hbp-sp6-guidebook/online_usecases/brain_area_circuit_in_silico_experiments/neocortex/mouse_sscx_preconfigured/mouse_sscx_preconfigured.html

**Comment by alex4200** [comment]
Thanks Luca

**Pull request merged**
